name: barristerkayserkamal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # main state management use
  flutter_riverpod: ^3.3.1
  # route related
  go_router: ^17.2.1
  # payment related
  app_links: ^7.0.0
  # storage
  shared_preferences: ^2.5.5
  # #1 Secure token storage (Android Keystore / iOS Keychain)
  flutter_secure_storage: ^8.1.0
  # environment secure variable
  flutter_dotenv: ^6.0.1

  # api services
  dio: ^5.9.2
  http_parser: ^4.1.2
  mime: ^2.0.0
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^3.1.2
  connectivity_plus: ^7.1.1

  # translator
  translator: ^1.0.4+1
  html: ^0.15.6

  # image related
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.2.1

  # ui related
  permission_handler: ^12.0.1
  readmore: ^3.0.0
  skeletonizer: ^2.1.3
  flutter_widget_from_html_core: ^0.17.0
  cupertino_icons: ^1.0.9

  # notification related
  flutter_local_notifications: ^21.0.0
  firebase_messaging: ^16.2.0
  firebase_core: ^4.7.0
  device_info_plus: ^13.0.0
  vector_math: ^2.2.0
  carousel_slider: ^5.1.2
  youtube_player_flutter: ^10.0.1
  dropdown_button2: 2.3.9
  url_launcher: ^6.3.1
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name:
    ^1.5.0 # dart run change_app_package_name:main com.new.package.name
    #  if need only android --android
    #  if need only iod --ios

flutter:
  uses-material-design: true

  # local all assets
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - .env # environment file add asset

  # local all font
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
